apiVersion: v1
kind: Pod
metadata:
  labels:
    app: message-service
  name: message-service
spec:
  containers:
  - image: reglocal:5000/message-service:v1
    name: message-service
    ports:
    - containerPort: 5031
    imagePullPolicy: Always
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  type: NodePort
  ports:
  - name: message-service
    port: 5031
    targetPort: 5031
    nodePort: 30531
  selector:
    app: message-service